### ISSUE TITLE
Copy/Content Edits across the site

### ISSUE THREAD

**Issue by anthonyvprakash** [atsign-foundation/atsign.dev#111]
Workflow for review
- [x] Review current content on the [staging website ](http://devstaging.atsign.wtf/docs/get-started/) Keep [SEO terms in mind](https://docs.google.com/document/d/1VY1Ui7UQ1pt2dBjBxsjerfV8DZ-h15Z2D48yam4bnMw/edit#heading=h.wth6vxka6rux)
- [x] Raise PR requests for the suggested changes and edits
- [x] Approve and push directly to website

**Comment by jenmonroe** [comment]
@ksanty  I'm happy to do as much of this as possible, or even all of it if you're busy. If we're both working on it, let's coordinate so we're not looking at the same stuff. Thanks!

**Comment by ksanty** [comment]
Kim, I can do the homepage, the dev program, community, showcase and 'the rest of it', if you want to grab the Functional Architecture and Resources? Sound good?

![Picture1](https://user-images.githubusercontent.com/74563278/124203958-c0396780-da92-11eb-994a-9243f05691b2.png)

**Comment by ksanty** [comment]
I am working on all pages under [Platform Architecture](http://devstaging.atsign.wtf/docs/functional_architecture/) and [Resources](http://devstaging.atsign.wtf/docs/resources/).  Will mark off as each page is finished here.  SEO is TBD.

- [x] [Platform Architecture homepage](http://devstaging.atsign.wtf/docs/functional_architecture/) - all links checked 
- [x] [Services](http://devstaging.atsign.wtf/docs/functional_architecture/services/) - all links checked, issue #117 submitted
- [x] [Libraries](http://devstaging.atsign.wtf/docs/functional_architecture/libraries/) - all links checked, issue #118 submitted also issue #120
- [x] [Dess](http://devstaging.atsign.wtf/docs/functional_architecture/dess/) - #161 
- [x] [Widgets](http://devstaging.atsign.wtf/docs/functional_architecture/widgets/) - in the middle of checking, issue #121
- [ ] [Verbs](http://devstaging.atsign.wtf/docs/functional_architecture/verbs/) - @nickelskevin descriptions or link to cookbook needed?
- [x] [Resources](http://devstaging.atsign.wtf/docs/resources/) - spelling errors and grammatical errors below
- [x] Tyler Time #137 , #138
- [ ] Glossary #139, do we need to create descriptions under each link?
- [ ] Community #140, do we need to create descriptions under each link?
- [ ] Data Privacy and Permissions Guide #141, #142
- [ ] Persistence and Keystore Guide #143, #144

**Comment by jenmonroe** [comment]
I've been working on the following sections:

- [x] Homepage
- [x] Showcase
- [ ] Community - Have edits but cannot access content to update
- [ ] @ dev program - Made edits where possible. All links need to be updated when other pages are ready. Also need to update @ Dev Program to @ dev Program, (but without the space) Filed here: https://github.com/atsign-foundation/atsign.dev/issues/155 
- [ ] tools & templates - Made edits where possible. Filed request for section I cannot edit here: https://github.com/atsign-foundation/atsign.dev/issues/156
- [ ] @ certification Need to meet with @aannttoo to finalize this content.
- [x] @ affiliates
- [x] Docs main page
- [x] get started
- [x] overview
- [x] specification No edits, though we say "@ sign user" and "user" in this doc. Okay to leave as is?
- [x] Set up the virtual environment
- [x] Sample Apps
- [x] Atmosphere
- [x] At hello world
- [x] At chats
- [x] At cookbook
- [ ] FAQ - Developer Commissions link is 404. Cookbook goes to Google Doc - is that correct?
- [x] About the @ platform
- [ ] SEO updates across the site - Training with @aannttoo week of 7/12 to get access to make edits
