### ISSUE TITLE
Widgets Page (Under Functional Architecture)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/atsign.dev#121]
Issues from - http://devstaging.atsign.wtf/docs/functional_architecture/widgets/

**The Onboarding Widget:**
- [x] All of the parameters in the “Onboarding” widget can be populated very easily with either methods from the project’s service file (e.g. getAtClientPreference**()**) - verified this formatting is correct
- [x] Removed comma issue #129 

**The Chatting Widget (word replacement?)**
- [x] One of the many things you can do after successfully authenticating an @sign is providing one-to-one text messaging! To do this, you’ll need the at_chat_flutter **dependency (should dependency read widget instead?)** sent a note to @nickelskevin 
- [ ] Github Libraries repo needs to be updated  #118 and #120.  

**The Contacts Widget**
- [x] Changed spelling from Initialised to Initialized issue #130 
- [ ] Github Widgets repo needs to be updated #136
