### ISSUE TITLE
Refine checklist template

### ISSUE THREAD

**Issue by jenmonroe** [atsign-foundation/atsign.dev#272]
- [x] [Update Git template](https://github.com/atsign-foundation/apps/issues/233) @ksanty 
- [x] Consolidate app store and google play launch checklists into [one list organized by task](https://docs.google.com/spreadsheets/d/10DXqnMEPDL6y8DHqS8J4TyRWHiqfu-y_ObxABNjFRDQ/edit#gid=0)
- [x] Team to review
